groups:
  - name: targets
    rules:
      - alert: monitor_service_down
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Monitor service is non-operational"
          description: "The service {{ $labels.instance }} is down."

  - name: host
    rules:
      - alert: high_cpu_load
        expr: node_load1 > 2
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Server is under high load"
          description: "The Docker host is under high load. The average load (1m) is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

      - alert: high_memory_load
        expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes) * 100 > 85
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Server memory is almost full"
          description: "The Docker host memory usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

      - alert: high_storage_load
        expr: (node_filesystem_size_bytes{fstype="aufs"} - node_filesystem_free_bytes{fstype="aufs"}) / node_filesystem_size_bytes{fstype="aufs"} * 100 > 85
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Server storage is almost full"
          description: "The Docker host storage usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."
